# ************************************************************************** #
#                                                                            #
#                                                        :::      ::::::::   #
#   Makefile                                           :+:      :+:    :+:   #
#                                                    +:+ +:+         +:+     #
#   By: gsheev <gsheev@student.21-school.ru>       +#+  +:+       +#+        #
#                                                +#+#+#+#+#+   +#+           #
#   Created: 2021/10/28 16:00:01 by gsheev            #+#    #+#             #
#   Updated: 202#   Updated: 2021/12/28 23:07:47 by gsheev           ###   ########.fr       #                                                              #
# ************************************************************************** #

SRCS = ft_atoi.c ft_isascii.c ft_memcmp.c ft_putendl_fd.c ft_strdup.c ft_strlen.c ft_strtrim.c ft_bzero.c ft_isdigit.c ft_memcpy.c ft_putnbr_fd.c ft_striteri.c ft_strmapi.c ft_substr.c ft_calloc.c ft_isprint.c ft_memmove.c ft_putstr_fd.c ft_strjoin.c ft_strncmp.c ft_tolower.c ft_isalnum.c ft_itoa.c ft_memset.c ft_split.c ft_strlcat.c ft_strnstr.c ft_toupper.c ft_isalpha.c ft_memchr.c ft_putchar_fd.c ft_strchr.c ft_strlcpy.c ft_strrchr.c

SRCDIR = ./

OBJS = ${SRCS:.c=.o} 

OBJDIR = ./

HEADER = libft.h

NAME = libft.a

CC = gcc

CFLAGS = -Wall -Wextra -Werror

RM = rm -f

NORM = norminette

all: ${NAME}

$(OBJDIR)%.o: $(SRCDIR)%.c $(HEADER)
	@test -d $(OBJDIR) || mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -c $< -o $@  

${NAME}: $(addprefix ${OBJDIR},${OBJS})
	ar rc $(NAME) $(addprefix ${OBJDIR},${OBJS})
	ranlib $(NAME)

clean:
	${RM} $(addprefix ${OBJDIR},${OBJS})

fclean:	clean
	${RM} ${NAME}

re:	fclean all

norm:
	@$(NORM) $(addprefix $(SRCDIR),$(SRCS)) $(HEADER)
